### ISSUE TITLE
CSS Classes and Multiple Imaged Posts

### ISSUE THREAD

**Issue by Rosenstein** [HaydenElza/instagram-image-click#1]
Recent update of Instagram's class names broke the script. Easy to fix tho'.
Also, it's not working with multiple images in a post (eg. https://www.instagram.com/p/BVWWh3JAMcq/?taken-by=imgur).

**Comment by HaydenElza** [comment]
I think commits a2f4a7d4f9e6cfb9cc522a5660c7bc962fe02bd7 and 4d51bab249c957d4929b09ab82d693bf58f16855 address these two issues. I thought I had it figured out in the first commit but ended up pushing a second because of some weird behavior for the post slideshows.

Thanks for letting me know about the changes!
